site_name: sushipy

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: deep orange
    features:
        - navigation.tabs
        - navigation.sidebar
plugins:
    - search
    - autolinks

nav:
    - Home: index.md
    - Documentation:
          - Welcome: main.md
          - Getting started: getting-started.md
          - Performance: performance.md
          - Debugging: debugging.md
