site_name: sushi

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: white
    features:
        - navigation.tabs
        - navigation.sidebar
    logo: assets/logo.png
    favicon: images/favicon.ico

plugins:
    - search
    - autolinks

nav:
    - Home: index.md
    - Documentation:
          - Welcome: main.md
          - Getting started: getting-started.md
          - Performance: performance.md
          - Debugging: debugging.md
