site_name: sushi

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: white
    features:
        - navigation.tabs
        - navigation.sidebar
    logo: assets/logo.png
    favicon: images/favicon.ico

plugins:
    - search
    - autolinks

nav:
    - Home: index.md
    - Documentation:
          - Welcome: main.md
          - Getting started: getting-started.md
          - Configuration:
                - Basic: configuration/basic.md
                - Advanced: configuration/advanced.md

          - Performance: performance.md
          - Debugging: debugging.md

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    - admonition
    - pymdownx.details
